kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kubeflow-nas-mnist
  namespace: orain
spec:
  storageClassName: example-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

