apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-09-10T10:29:47Z"
  generation: 1
  labels:
    app: tensorboard
    kustomize.component: tensorboard
  name: tensorboard
  namespace: kubeflow
  resourceVersion: "4913082"
  selfLink: /apis/extensions/v1beta1/namespaces/kubeflow/deployments/tensorboard
  uid: afd93611-be26-4591-ad5c-964554788f9a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      kustomize.component: tensorboard
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tensorboard
        kustomize.component: tensorboard
    spec:
      containers:
        - args:
            - --logdir=logs
            - --port=6006
          command:
            - /usr/local/bin/tensorboard
          image: tensorflow/tensorflow:1.8.0
          imagePullPolicy: IfNotPresent
          name: tensorboard
          ports:
            - containerPort: 6006
              protocol: TCP
          resources:
            limits:
              cpu: "4"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2019-09-10T10:29:47Z"
      lastUpdateTime: "2019-09-10T10:29:50Z"
      message: ReplicaSet "tensorboard-5f685f9d79" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2019-11-02T07:20:35Z"
      lastUpdateTime: "2019-11-02T07:20:35Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1